include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_const_constructors: false
