include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
    - example/**
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
    prefer_const_constructors: false
    sort_constructors_first: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    comment_references: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    prefer_const_declarations: false
    directives_ordering: false